// skillsData.ts
import { SkillsMap } from "./types";

// Define skills by category (representing a hash map data structure)
export const skillsMap: SkillsMap = {
  frontend: [
    { name: "React", icon: "react", level: 90 },
    { name: "Next.js", icon: "nextdotjs", level: 85 },
    { name: "TypeScript", icon: "typescript", level: 88 },
    { name: "Tailwind CSS", icon: "tailwindcss", level: 92 },
    { name: "JavaScript", icon: "javascript", level: 95 },
    { name: "HTML5", icon: "html5", level: 98 },
    { name: "CSS3", icon: "css3", level: 90 },
    { name: "Redux", icon: "redux", level: 82 },
    { name: "Vue.js", icon: "vuedotjs", level: 75 },
    { name: "Sass", icon: "sass", level: 85 },
    { name: "Angular", icon: "angular", level: 78 },
    { name: "Svelte", icon: "svelte", level: 72 },
    { name: "Astro", icon: "astro", level: 80 },
    { name: "Framer Motion", icon: "framer", level: 83 },
    { name: "Styled Components", icon: "styledcomponents", level: 87 },
    { name: "Material UI", icon: "mui", level: 84 },
    { name: "Chakra UI", icon: "chakraui", level: 86 },
    { name: "Bootstrap", icon: "bootstrap", level: 89 },
    { name: "Webpack", icon: "webpack", level: 76 },
    { name: "Vite", icon: "vite", level: 81 },
  ],
  backend: [
    { name: "Node.js", icon: "nodedotjs", level: 88 },
    { name: "Express", icon: "express", level: 85 },
    { name: "Python", icon: "python", level: 80 },
    { name: "Django", icon: "django", level: 75 },
    { name: "GraphQL", icon: "graphql", level: 78 },
    { name: "REST API", icon: "openapi", level: 90 },
    { name: "NestJS", icon: "nestjs", level: 70 },
    { name: "Spring Boot", icon: "spring", level: 65 },
    { name: "Laravel", icon: "laravel", level: 73 },
    { name: "Ruby on Rails", icon: "rails", level: 68 },
    { name: "Flask", icon: "flask", level: 77 },
    { name: "FastAPI", icon: "fastapi", level: 82 },
    { name: "ASP.NET Core", icon: "dotnet", level: 71 },
    { name: "Golang", icon: "go", level: 74 },
    { name: "Deno", icon: "deno", level: 69 },
    { name: "Strapi", icon: "strapi", level: 79 },
    { name: "Prisma", icon: "prisma", level: 84 },
    { name: "tRPC", icon: "trpc", level: 76 },
  ],
  database: [
    { name: "MongoDB", icon: "mongodb", level: 85 },
    { name: "PostgreSQL", icon: "postgresql", level: 82 },
    { name: "MySQL", icon: "mysql", level: 80 },
    { name: "Redis", icon: "redis", level: 75 },
    { name: "Firebase", icon: "firebase", level: 88 },
    { name: "Supabase", icon: "supabase", level: 78 },
    { name: "SQLite", icon: "sqlite", level: 83 },
    { name: "DynamoDB", icon: "amazondynamodb", level: 72 },
    { name: "Cassandra", icon: "apachecassandra", level: 65 },
    { name: "Elasticsearch", icon: "elasticsearch", level: 70 },
    { name: "Neo4j", icon: "neo4j", level: 68 },
    { name: "CouchDB", icon: "apachecouchdb", level: 67 },
    { name: "MariaDB", icon: "mariadb", level: 76 },
    { name: "Oracle", icon: "oracle", level: 69 },
    { name: "MS SQL", icon: "microsoftsqlserver", level: 73 },
    { name: "Fauna", icon: "fauna", level: 71 },
    { name: "Firestore", icon: "firebase", level: 81 },
  ],
  tools: [
    { name: "Git", icon: "git", level: 95 },
    { name: "Docker", icon: "docker", level: 80 },
    { name: "AWS", icon: "amazonaws", level: 78 },
    { name: "Jenkins", icon: "jenkins", level: 70 },
    { name: "GitHub", icon: "github", level: 92 },
    { name: "VSCode", icon: "visualstudiocode", level: 95 },
    { name: "Figma", icon: "figma", level: 75 },
    { name: "Kubernetes", icon: "kubernetes", level: 72 },
    { name: "GitHub Actions", icon: "githubactions", level: 85 },
    { name: "CircleCI", icon: "circleci", level: 74 },
    { name: "Terraform", icon: "terraform", level: 68 },
    { name: "Jira", icon: "jira", level: 83 },
    { name: "Notion", icon: "notion", level: 87 },
    { name: "Postman", icon: "postman", level: 89 },
    { name: "Sentry", icon: "sentry", level: 77 },
    { name: "Vercel", icon: "vercel", level: 88 },
    { name: "Netlify", icon: "netlify", level: 86 },
    { name: "Heroku", icon: "heroku", level: 82 },
    { name: "Google Cloud", icon: "googlecloud", level: 73 },
    { name: "Azure", icon: "microsoftazure", level: 71 },
  ],
  languages: [
    { name: "JavaScript", icon: "javascript", level: 95 },
    { name: "TypeScript", icon: "typescript", level: 88 },
    { name: "Python", icon: "python", level: 80 },
    { name: "Java", icon: "java", level: 70 },
    { name: "C++", icon: "cplusplus", level: 65 },
    { name: "Rust", icon: "rust", level: 60 },
    { name: "Go", icon: "go", level: 72 },
    { name: "PHP", icon: "php", level: 75 },
    { name: "C#", icon: "csharp", level: 68 },
    { name: "Ruby", icon: "ruby", level: 67 },
    { name: "Swift", icon: "swift", level: 63 },
    { name: "Kotlin", icon: "kotlin", level: 66 },
    { name: "Dart", icon: "dart", level: 71 },
    { name: "Scala", icon: "scala", level: 61 },
    { name: "Haskell", icon: "haskell", level: 57 },
    { name: "Elixir", icon: "elixir", level: 59 },
    { name: "Lua", icon: "lua", level: 64 },
    { name: "Shell", icon: "gnubash", level: 76 },
  ],
  cloudAndDevops: [
    { name: "AWS", icon: "amazonaws", level: 78 },
    { name: "Google Cloud", icon: "googlecloud", level: 73 },
    { name: "Azure", icon: "microsoftazure", level: 71 },
    { name: "Docker", icon: "docker", level: 80 },
    { name: "Kubernetes", icon: "kubernetes", level: 72 },
    { name: "Terraform", icon: "terraform", level: 68 },
    { name: "Jenkins", icon: "jenkins", level: 70 },
    { name: "GitHub Actions", icon: "githubactions", level: 85 },
    { name: "CircleCI", icon: "circleci", level: 74 },
    { name: "Ansible", icon: "ansible", level: 66 },
    { name: "Prometheus", icon: "prometheus", level: 69 },
    { name: "Grafana", icon: "grafana", level: 67 },
    { name: "ELK Stack", icon: "elasticstack", level: 65 },
    { name: "Nginx", icon: "nginx", level: 77 },
    { name: "CI/CD", icon: "githubactions", level: 83 },
    { name: "ArgoCD", icon: "argo", level: 64 },
    { name: "Pulumi", icon: "pulumi", level: 62 },
  ],
};

// Get categories
export const categories = Object.keys(skillsMap);

// Get all skill icons for cloud visualization
export const getAllSkillIcons = (): string[] => {
  return Object.values(skillsMap)
    .flat()
    .map((skill) => skill.icon);
};
